# LingCard/config.yaml
game_settings:
  initial_hp: 15
  initial_hand_size: 3
  characters_per_player: 3
  # deck_composition: 已移除默认配置，现在使用配卡界面的自定义配置
  # 新的配卡系统要求每个玩家自定义10张卡的组合

team_effects:
  - characters: ["Jun", "Liuli"]
    effect: JUN_LIULI
    description: "俊+琉璃组合：每回合第一次攻击+1"
  - characters: ["Cafe", "Xinhe"]
    effect: CAFE_XINHE
    description: "Cafe+星河组合：每回合额外抽取2张卡"
  - characters: ["Yangguang", "Liuli"]
    effect: YANGGUANG_LIULI
    description: "阳光+琉璃组合：免除第一次伤害"